ALL: act7
.PHONY=clean, act2, act3, act7

clean:
	\rm -rf act2 act3 act4

act2: tarea1.c
	gcc -o act2 tarea1.c -lGL -lGLU -lglut

act3: tarea2.c
	gcc -o act3 tarea2.c -lGL -lGLU -lglut

act4: actividad4_monzalvoDaniel_a01021514.c
	gcc -o act4 actividad4_monzalvoDaniel_a01021514.c -lGL -lGLU -lglut

act7: tarea7.cpp
	g++ --std=c++11 -o act7 tarea7.cpp -lGL -lGLU -lglut
