ALL: act4
.PHONY=clean, act2, act3

clean:
	\rm -rf act2 act3 act4

act2: tarea1.c
	gcc -o act2 tarea1.c -lGL -lGLU -lglut

act3: tarea2.c
	gcc -o act3 tarea2.c -lGL -lGLU -lglut

act4: tarea4.c
	gcc -o act4 tarea4.c -lGL -lGLU -lglut
